version: "3.9"

services:
  db:
    container_name: mysql
    image: mysql:8.0
    # M1チップでも動くように
    platform: linux/x86_64
    # ローカルの/data/dbをコンテナの/var/lib/mysqlにマウンティング
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    # 環境変数
    env_file:
      - .env
    # デフォルトの認証プラグインをMySQL8系用に変更
    command: --default-authentication-plugin=mysql_native_password
  app:
    container_name: app
    build:
      context: .
      dockerfile: containers/django/Dockerfile
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
  web:
    container_name: web
    image: nginx
    volumes:
      # - ./containers/nginx/default.conf:/etc/nginx/default.conf
      - ./containers/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./containers/uwsgi/uwsgi_params:/etc/nginx/uwsgi_params
    # ホストの8080番ポートにアクセスするとコンテナの80番(HTTP)ポートにアクセスできる
    ports:
      - "80:80"
    depends_on:
      - app
volumes:
  db_data:
